name: CI - Android

on:
    push:
        branches:
            - main
#test
jobs:
    build:
        runs-on: ubuntu-20.04
        #    env:
        #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            #      - name : Test Build
            #        uses: QiubyZ/kivy-build@v1
            #        with:
            #          buildozer_cmd: |
            #            echo 'yes' | buildozer -v android debug
            - uses: actions/checkout@v4
            - name: Check Dir
              run: |
                  cd ${{ github.workspace }}
                  ls -l -a
            - name: update apt
              run: apt list --upgradable
            - name: Build APK
              uses: digreatbrian/buildozer-action@v2

              with:
                  python-version: 3.8
                  buildozer-cmd: buildozer -v android debug
                  work-dir: ${{ github.workspace }}

            - name: Buat Rilis Baru
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v1
                  name: Clock #Test Release
                  files: ${{ github.workspace }}/bin/*.apk
                  draft: false
                  prerelease: false
                  generate_release_notes: false
