name: CI - Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            python3-pip \
            openjdk-17-jdk \
            zip \
            unzip \
            libtinfo6 \
            libncurses5 \
            zlib1g-dev

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug
          work-dir: ${{ github.workspace }}

      - name: Buat Rilis Baru
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1
          name: Clock #Test Release
          files: ${{ github.workspace }}/bin/*.apk
          draft: false
          prerelease: false
          generate_release_notes: false
